name: app_chat
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_spinkit: ^4.1.2+1

  firebase_auth: ^3.1.2
  firebase_messaging: ^10.0.8
  firebase_storage: ^10.0.4
  cloud_firestore: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - assets/default.jpg
  fonts:
    - family: FlutterIcons
      fonts:
        - asset: assets/fonts/FlutterIcons.ttf
